update

diff --git a/blacklist b/blacklist
--- a/blacklist
+++ b/blacklist
@@ -1,7 +1,7 @@
 #!/bin/bash
-# $Id: blacklist,v 1.121 2018/06/01 18:34:06 fulford Exp $
+# $Id: blacklist,v 1.122 2018/06/01 18:42:47 fulford Exp $
 # $Source: /src/admin/usr/local/etc/RCS/blacklist,v $
-# $Revision: 1.121 $
+# $Revision: 1.122 $
 # Author C W Fulford.
 # Copyright 2017 (c) C W Fulford.
 # Licensed for public use under the LGPL, .
@@ -10,17 +10,18 @@
 cmd=`basename $0`
 
 config=/usr/local/etc/blacklist.cf
-ver=`echo "$Id: blacklist,v 1.121 2018/06/01 18:34:06 fulford Exp $"|awk '{print $3,$4,$5}'`
+ver=`echo "$Id: blacklist,v 1.122 2018/06/01 18:42:47 fulford Exp $"|awk '{print $3,$4,$5}'`
 sysadmin=fulford@fulford.net
 
 syntax="$cmd  [-l] | [-V]"
 while [ $# -gt 0 ] ;do
 	case $1 in 
 		-l) log=:;shift;;			
-		-V) echo "$cmd $Revision: 1.121 $ $Date: 2018/06/01 18:34:06 $"|awk '{print $1,$3,$6}';exit;;  
+		-V) echo "$cmd $Revision: 1.122 $ $Date: 2018/06/01 18:42:47 $"|awk '{print $1,$3,$6}';exit;;  
 	esac
 done
 export ADMINHOST=admin
+export ERROR=0
 export MAILHOST=mail
 export LOG=/var/log/blacklist/blacklist.log
 export TARGET=access
@@ -31,7 +32,7 @@ export SRC=$SRCDIR/$TARGET
 export DEST=$TARGETDIR/$TARGET
 export TMP=/tmp/${TARGET}
 
-_error () { echo "$cmd: error on line $1";  ;}
+_error () { echo "$cmd: error near line $1";  ;}
 _end () { echo -n 'Press "Return" to continue';read ought </dev/tty ;}
 
 address=`grep "^Return-Path: " | sed -e 's/Return-Path: <\([^>]*\)>/\1/'`
@@ -69,17 +70,20 @@ if [ "$answer" == "y" ];then
 		echo \"SRCDIR = $SRCDIR\"
 		cd $SRCDIR
 		hostname	
-		co -l -q $TARGET ||{ _error; _end ;}
+		co -l -q $TARGET
+		ERROR=$? 
 		echo $BLACKLIST >$TMP
 		cat $TARGET >>$TMP
 		# makemap will fail if there are duplicate entries in the
 		# access file
 		cat $TMP|sort -u > $TARGET  #2>/dev/null
 		cat $TARGET|ssh $MAILHOST sudo dd of=$DEST
-		/usr/bin/ci -m -q $TARGET ||{ _error $LINENO;_end ;}
+		/usr/bin/ci -m -q $TARGET 
+		ERROR=$?
 		rm $TMP
-		exit
+		exit $ERROR
 		"
+	[ $ERROR -gt 0 ] && { _error $LINENO; _end ;}
 	ssh $MAILHOST "
 		set -x
 		hostname
